<?php

/**
 * Implements hook_file_presave().
 */
function pori_scald_image_file_presave($file) {
  $full_url = file_create_url($file->uri);
  $parsed_url = parse_url($full_url);

  // Expire Varnish cache for the new file.
  varnish_expire_cache([$parsed_url['path'] => $parsed_url['path']]);
  varnish_purge($parsed_url['host'], $parsed_url['path']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pori_scald_image_form_scald_atom_add_form_add_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'pori_scald_image_form_validation';
}

/**
 * Custom form validation.
 */
function pori_scald_image_form_validation($form, &$form_state) {
  foreach ($form_state['values']['file'] as &$file) {
    $old_uri = 'public://atoms/files/' . $file['name'];
    $files = file_load_multiple([], ['uri' => $old_uri]);
    $old_file = reset($files);

    if (!empty($old_file)) {
      file_delete($old_file, TRUE);
    }
 }
  return TRUE;
}

/**
 * Implements hook_entity_load().
 */
function pori_scald_image_entity_load($entities, $type) {
  if ($type == 'scald_atom') {
    global $language;

    foreach ($entities as $atom) {
      $atom_fields = &drupal_static(__FUNCTION__ . $atom->type);
      if (!isset($atom_fields)) {
        $atom_fields = field_read_fields(array('entity_type' => $type, 'bundle' => $atom->type));
      }

      // Check every field that is of type image
      foreach ($atom_fields as $key => $field) {
        if ($field['type'] == 'image') {
          $alt_field_key = 'field_alt_text';
          $title_field_key = 'field_title_text';
          if (isset($atom->{$key}[LANGUAGE_NONE][0])) {
            // Trying to find related alternative text field for scald-image.
            if (isset($atom->{$alt_field_key}[$language->language][0]['safe_value'])) {
              $alt_text = $atom->{$alt_field_key}[$language->language][0]['safe_value'];
            }
            else if (isset($atom->{$alt_field_key}[$atom->language][0]['safe_value'])) {
              $alt_text = $atom->{$alt_field_key}[$atom->language][0]['safe_value'];
            }
            if (isset($atom->{$title_field_key}[$language->language][0]['safe_value'])) {
              $title_text = $atom->{$title_field_key}[$language->language][0]['safe_value'];
            }
            else if (isset($atom->{$title_field_key}[$atom->language][0]['safe_value'])) {
              $title_text = $atom->{$title_field_key}[$atom->language][0]['safe_value'];
            }
            if (isset($alt_text)) {
              $atom->{$key}[LANGUAGE_NONE][0]['alt'] = $alt_text;
              $atom->{$key}[LANGUAGE_NONE][0]['title'] = $title_text;
            } else {
              $atom->{$key}[LANGUAGE_NONE][0]['alt'] = '';
              $atom->{$key}[LANGUAGE_NONE][0]['title'] = '';
            }
          }
        }
      }
    }
  }
}

